eset <- read.table("SNC_vs_VTA_combat_processed.txt", row.names = 1, head = TRUE)
targets <- read.table("SNC_vs_VTA_sup.txt", row.names =1, head = TRUE)
Treat <- factor(targets$Region, levels = c("VTA","SNC"))
design <- model.matrix(~Treat)
fit <- lmFit(eset, design)
plotMA(fit, coef = ncol(fit))
fit <- eBayes(fit)
output <- topTable(fit, number = Inf, coef = "TreatSNC")
write.table(output, "Human_sig_output.txt", sep = '\t')
