library(Seurat)
library(dplyr)
library(ggplot2)
library(RColorBrewer)
library(plotly)
library(viridisLite)
hMLO4.data <- Read10X(data.dir = "MLO4_filtered_feature_bc_matrix/")
hMLO4 <- CreateSeuratObject(counts = hMLO4.data, project = 'hMLO4', min.cells = 3, min.features = 200)
hMLO4[["percent.mt"]] <- PercentageFeatureSet(hMLO4, pattern = "^MT-")
VlnPlot(object = hMLO4, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
#FeatureScatter(hMLO4, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
hMLO4.nFeat = hMLO4@meta.data$nFeature_RNA
hMLO4.mito = hMLO4@meta.data$percent.mt
med = median(hMLO4.nFeat)
mad.val = median(abs(hMLO4.nFeat - med))
lower.limit = med - 2*mad.val
hMLO4.filtered <- subset(hMLO4, subset = nFeature_RNA > lower.limit & percent.mt > -Inf & percent.mt < 5)
hMLO4.filtered.norm <- NormalizeData(object = hMLO4.filtered, normalization.method = 'LogNormalize', scale.factor = 10000)
hMLO4 <- FindVariableFeatures(hMLO4.filtered.norm, selection.method = "vst", nfeatures = 2000)
top10 <- head(VariableFeatures(hMLO4), 10)
plot1 <- VariableFeaturePlot(hMLO4)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
all.genes <- rownames(hMLO4)
hMLO4 <- ScaleData(hMLO4, features = all.genes)
hMLO4 <- RunPCA(hMLO4, features = VariableFeatures(object = hMLO4))
DimPlot(object = hMLO4, reduction = "pca")
DimHeatmap(hMLO4, dims = 1:20, cells = 500, balanced = TRUE)
hMLO4 <- JackStraw(hMLO4, num.replicate = 100, dims = 25)
hMLO4 <- ScoreJackStraw(hMLO4, dims = 1:25)
JackStrawPlot(hMLO4, dims = 1:25)
ElbowPlot(hMLO4,ndims = 50)

hMLO4 <- FindNeighbors(hMLO4, dims = 1:17)
hMLO4 <- FindClusters(hMLO4, resolution = 0.8)
hMLO4 <- RunUMAP(hMLO4, dims = 1:17)
hMLO4 <- RunTSNE(object = hMLO4, dims.use = 1:14, do.fast = TRUE)
DimPlot(hMLO4, reduction = "umap", label = TRUE, label.size = 5, label.box = TRUE)
DimPlot(hMLO4, reduction = 'tsne')
FeaturePlot(hMLO4, features = c('DDC','KCNJ6','TH','PITX3'))
DotPlot(hMLO4, features = c('DDC','KCNJ6','TH','PITX3'))
#A8/RRF (TH, PITX3, SOX6+, ALDH1A1), A9/SN (Th, PITX3, GIRK2(KCNJ6), ALDH1A1), A10/VTA (TH, PITX3, CALB1) 
#M'S126 >> dimension 14,resolution 0.8
##Options : 
#hM'LO3 >> dimension 19, resolution 0.8
#hM'LO4 >> dimension 17, resolution 0.8
hMLO4.markers <- FindAllMarkers(hMLO4,only.pos = TRUE,min.pct = 0.25, logfc.threshold = 0.25)
Large.div.markers <- FindMarkers(hMLO4, ident.1 = 3, ident.2 = 0, only.pos = TRUE)
hMLO4.markers %>% group_by(cluster) %>% top_n(n = 2, wt = avg_log2FC)
Cell_A9_SN_GeneList <- list(c('DDC','TH','PITX3','KCNJ6','ALDH1A1'))
Cell_A10_VTA_GeneList <- list(c('DDC','KCNJ6','TH','PITX3','CALB1'))
Cell_A8_RRF_GeneList <- list(c('TH','PITX3','SOX6','ALDH1A1'))
#DoHeatmap(object = hMLO4, features = c('TH','PITX3','ALDH1A1','SOX6','KCNJ6','CALB1'), label = TRUE)
hMLO4.test <- AddModuleScore(object = hMLO4, features = Cell_A10_VTA_GeneList, name = 'A10.VTA')
FeaturePlot(hMLO4.test, features = 'A10.VTA1')

new.cluster.ids <- c(0,1,2,3,'Dopaminergic',5,6,7,'Glutamatergic',9,10,11,12)
names(new.cluster.ids) <- levels(hMLO4)
hMLO4 <- RenameIdents(hMLO4, new.cluster.ids)

hMLO4.DA <- subset(hMLO4, idents = c(3))
hMLO4.DA <- FindVariableFeatures(hMLO4.DA, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(hMLO4.DA)
hMLO4.DA <- ScaleData(hMLO4.DA, features = all.genes)
hMLO4.DA <- RunPCA(hMLO4.DA, features = VariableFeatures(object = hMLO4.DA))
hMLO4.DA <- JackStraw(hMLO4.DA, num.replicate = 100, dims = 20)
hMLO4.DA <- ScoreJackStraw(hMLO4.DA, dims = 1:20)
JackStrawPlot(hMLO4.DA, dims = 1:20)
ElbowPlot(hMLO4.DA,ndims = 50)
hMLO4.DA <- FindNeighbors(hMLO4.DA, dims = 1:7)
hMLO4.DA <- FindClusters(hMLO4.DA, resolution = 0.8)
hMLO4.DA <- RunUMAP(hMLO4.DA, dims = 1:7)
DimPlot(hMLO4.DA, reduction = "umap")
hMLO4.DA.markers <- FindAllMarkers(hMLO4.DA,only.pos = TRUE,min.pct = 0.25, logfc.threshold = 0.25)
FeaturePlot(hMLO4, 'SOX6')
hMLO4.DA.SN <- subset(hMLO4, subset = (OTX2 > 0) & (SOX6 > 0), idents = c(4))
pp <- DimPlot(hMLO4, cells.highlight = WhichCells(hMLO4, ident = 4, expression = OTX2 > 0 & SOX6 == 0))

DimPlot(hMLO4, cells.highlight = WhichCells(hMLO4, ident = 4, expression = OTX2 == 0 & SOX6 == 0)) + 
  scale_color_manual(labels = c(NA, 'SOX6- / OTX2-'), values = c("grey","blue")) + 
  ggtitle('hMLO4 SOX6- / OTX2-') + theme(plot.title = element_text(size = 18))

dim(hMLO4)
